### ISSUE TITLE
Clear method only removes half of the view's children per call

### ISSUE THREAD

**Issue by yissachar** [ahome-it/ahome-titanium#9] opened 2015-05-05 20:37 UTC
As a workaround you can wrap it in a while loop:

```
while(view.getChildCount() > 0) {
  view.clear();
}
```

I took a look at the code for clear but nothing obvious jumps out to me as to why this would be happening.

**Comment by eemi2010** [comment] 2015-05-06 20:48
Thx for reporting. Will have a look

**Comment by eemi2010** [comment] 2015-05-20 20:31
I cant reproduce this. Can you please please provide a simple use case reproducing the error.

**Comment by yissachar** [comment] 2015-05-20 20:39
Here is a very simple test case:

```
public class Helloti4j extends TiEntryPoint {

    @Override
    public void onStart() {
        Window window = new Window();
        window.setBackgroundColor(Color.WHITE);
        window.setLayout(View.ViewLayout.VERTICAL);

        Label first = new Label("first");
        Label second = new Label("second");
        Label third = new Label("third");
        window.add(first);
        window.add(second);
        window.add(third);

        window.open();

        window.clear();
    }

}
```

We would expect no labels to exist on the window after `clear()` but instead `second` is still visible. If `clear()` is called again `second` is removed.

**Comment by eemi2010** [comment] 2015-05-20 20:45
Thx Will have a look asap.

**Comment by eemi2010** [comment] 2015-05-20 21:21
Please note that as of 4.1.0 we broke constructors taking a string as argument. Those contructors now set the id of the component. Not the text like in the case of label.
We had to do this to create Alloy support.

**Comment by eemi2010** [comment] 2015-05-20 21:45
Should be fixed with https://github.com/ahome-it/ahome-titanium/commit/0e37d80b1de55e67de24cb1b3efe40162cd78377

**Closed as completed by eemi2010** 2015-05-20 21:45 UTC
Labels: bug

**Comment by yissachar** [comment] 2015-05-20 22:14
Indeed it works correctly now :+1:
